version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/
    links:
      - php-fpm

  php-fpm:
    build: ./docker/php
    volumes:
      - ./:/var/www/
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    links:
      - mysql

  php-cli:
    build: ./docker/php
    volumes:
      - ./:/var/www/
    links:
      - mysql
    tty: true

  mysql:
    image: mariadb
    tty: true
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - '33061:3306'
    environment:
      TZ: 'Europe/Moscow'
      MYSQL_ROOT_PASSWORD: '123'
      SERVICE_NAME: mysql
