version: '3.7'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/
    links:
      - php

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www/
    links:
      - mysql
    networks:
      internal:
        ipv4_address: 172.25.0.12

  php-cli:
    build: ./docker/php
    container_name: php-cli
    volumes:
      - ./:/var/www/
    links:
      - mysql
    tty: true

  mysql:
    image: mariadb
    container_name: mariadb
    tty: true
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      TZ: 'Europe/Moscow'
      MYSQL_ROOT_PASSWORD: '123'
      SERVICE_NAME: mysql
